terraform {
  required_version = ">= 1.3.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.5"
    }
  }
}

provider "aws" {
  access_key = var.aws_access_key
  secret_key = var.aws_secret_key
  region     = var.aws_region
}

module "keypair" {
  source = "./modules/keypair"

  key_name = var.key_name
  keys_dir = "${path.module}/keys"
}

module "vpc" {
  source = "./modules/vpc"

  name                 = var.vpc_name
  vpc_cidr             = var.vpc_cidr
  public_subnet_cidrs  = var.public_subnet_cidrs
  private_subnet_cidrs = var.private_subnet_cidrs
  tags                 = var.tags
}

module "ec2_instances" {
  source = "./modules/ec2"

  master_count         = 2
  agent_count          = 4
  ami_id               = var.ami_id
  instance_type        = var.instance_type
  key_name             = module.keypair.key_name
  vpc_id               = module.vpc.vpc_id
  subnet_ids           = module.vpc.public_subnet_ids
  vpc_cidr             = module.vpc.vpc_cidr
  ssh_allowed_cidrs    = var.ssh_allowed_cidrs
  instance_name_prefix = var.instance_name_prefix
  tags                 = var.tags
}

# Instances are created in order: masters (indices 0-1) then agents (indices 2-5)
locals {
  master_public_ips = slice(module.ec2_instances.public_ips, 0, 2)
  agent_public_ips  = slice(module.ec2_instances.public_ips, 2, 6)
}

resource "local_file" "ansible_inventory" {
  filename        = "${path.module}/ansible/inventory/hosts.ini"
  file_permission = "0644"
  content         = <<-EOT
    # Auto-generated by Terraform — do not edit manually.
    # Re-run `terraform apply` to refresh after instance changes.

    [master]
    master-1  ansible_host=${local.master_public_ips[0]}
    master-2  ansible_host=${local.master_public_ips[1]}  master_host=master-1

    [agents]
    agent-1  ansible_host=${local.agent_public_ips[0]}  master_host=master-1
    agent-2  ansible_host=${local.agent_public_ips[1]}  master_host=master-1
    agent-3  ansible_host=${local.agent_public_ips[2]}  master_host=master-1
    agent-4  ansible_host=${local.agent_public_ips[3]}  master_host=master-1

    # ── Group aliases ─────────────────────────────────────────────────────────────

    [masters:children]
    master

    [slaves:children]
    agents
  EOT
}
